org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false

kotlin.code.style=official
ksp.useKSP2=false

kotlin.daemon.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.compiler.execution.strategy=in-process
